- hosts: localhost
  vars:
    — repo_mount_path: “/root/software/”
   — dest_iso: “/dev/cdrom”
  tasks: 

   — name: create a folder.
     file: 
       path: /root/software
       state: directory
       mode: ‘0755’

  - name: mount ISO file to the created folder.
    mount:
       src: “{{dest_iso}}”
       path: “{{repo_mount_path}}”
       state: mounted
       fstype: “iso9660”

  - name: Mount ISO file permanently.
    lineinfile:
       dest: /etc/rc.d/rc.local
       line: mount /dev/cdrom /root/software/
       state: present
       create: yes

  - name: Make /etc/rc.d/rc.local file executable!!
    command: chmod +x /etc/rc.d/rc.local

  - name: Adding yum repository.
    yum_repository:
        name: dvd1 
        description: YUM AppStream repo
        baseurl: “file://{{repo_mount_path}}/AppStream”
        enabled: yes
       gpgcheck: no

  - name: Adding yum repository.
    yum_repository:
           name: dvd2
           description: YUM BaseOS repo
           baseurl: “file://{{repo_mount_path}}//BaseOS”
           enabled: yes
           gpgcheck: no

 - name: Adding docker repository.
   yum_repository:
      name: docker
      description: Docker_repository
      baseurl: “https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: no

  - name: Install Docker
    package:
      name: “docker-ce-18.06.3.ce-3.el7.x86_64”
      state: present
  
  - name: Start Docker services.
    service:
      name: “docker”
      state: started
 
  - pip: 
    name: docker
 
  - name: "Creating A WorkSpace on MN"
    file:
      path: /root/AnsibleTask
      state: directory

  - name: Copying Content Into Managed Node
    copy:
      src: "/root/web.html"
      dest: "/root/AnsibleTask"
    ignore_errors: yes

  - name: "Pull httpd docker image"
    docker_image:
      name: httpd
      pull: yes
      state: present

  - name: "Launch a docker container"
    docker_container:
      name: "web1_ansible"
      image: httpd
      state: started
      interactive: yes
      tty: yes
      exposed_ports:
      - "80"
      ports:
      - "8081:80"
      volumes:
      - /root/AnsibleTask/:/usr/local/apache2/htdocs/

  - name: "Retrieve docker container IP-address"
    community.general.docker_container_info:
      name: "web1_ansible"
    register: IP

  - name: "Docker Container IP-address"
    debug:
      var: IP.container.NetworkSettings.IPAddress

  - name: "Update docker conatiner Ip-address in ansible inventory file"
    blockinfile:
      path: "/root/ip.txt"
      block: |
              [docker]
              {{ IP.container.NetworkSettings.IPAddress }}



- hosts: docker
  tasks:
  - name: "configure httpd"
    template:
           src: "/root/you.html"
           dest: "/var/html/www"
